version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module-chrome:
    image: deeprqa/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-chrome:/usr/share/selenium-docker/test-output
  search-module-firefox:
    image: deeprqa/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-firefox:/usr/share/selenium-docker/test-output
  parabank-module-chrome:
    image: deeprqa/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=parabank-module.xml
    volumes:
    - ./output/parabank-result-chrome:/usr/share/selenium-docker/test-output
  parabank-module-firefox:
    image: deeprqa/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=parabank-module.xml
    volumes:
      - ./output/parabank-result-firefox:/usr/share/selenium-docker/test-output
